"""Core game logic: cards, engine, rules, helpers."""

from .card import (
    JOKER_DISPLAY_NAME_PT,
    RANK_ORDER_SEQUENCE,
    SUIT_MAP,
    SUIT_NAME_MAP,
    SUIT_NAMES_PT,
    SUIT_SYMBOLS,
    Card,
    Rank,
    Suit,
    create_canastra_deck,
    parse_hand,
)
from .constants import (
    ActionDescriptions,
    ActionKind,
    AIConfig,
    AppConfig,
    GameMode,
    GameRules,
    GameType,
    GameTypeStr,
    GameValidation,
    KnockType,
    TurnPhase,
    UIText,
)
from .engine import Engine, Player
from .game import (
    Game,
    can_form_sequence,
    can_form_triple,
    counts_as_wildcard_in_sequence,
    is_wildcard,
)
from .game_helpers import (
    detect_game_type,
    get_counterfactual_action,
    organize_hand,
    play_ai_turn,
)
from .rules_loader import RULES_BODY

__all__ = [
    "ActionDescriptions",
    "ActionKind",
    "AIConfig",
    "AppConfig",
    "Card",
    "Engine",
    "Game",
    "GameMode",
    "GameRules",
    "GameType",
    "GameTypeStr",
    "GameValidation",
    "JOKER_DISPLAY_NAME_PT",
    "KnockType",
    "Player",
    "RANK_ORDER_SEQUENCE",
    "RULES_BODY",
    "SUIT_MAP",
    "SUIT_NAME_MAP",
    "SUIT_NAMES_PT",
    "SUIT_SYMBOLS",
    "TurnPhase",
    "UIText",
    "can_form_sequence",
    "can_form_triple",
    "counts_as_wildcard_in_sequence",
    "create_canastra_deck",
    "detect_game_type",
    "get_counterfactual_action",
    "is_wildcard",
    "organize_hand",
    "parse_hand",
    "play_ai_turn",
    "Rank",
    "Suit",
]
